common: &common
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: fez
  password:

development:
  <<: *common
  database: fez_development

test:
  <<: *common
  database: fez_test

production:
  <<: *common
  database: fez_production
